#!/usr/bin/env bash

CONFIG_DIR=/usr/local/etc/xray
CONFIG=$CONFIG_DIR/config.json
CLIENT_CONFIG_TEMPLATE=$CONFIG_DIR/config_client.json
IP=$(curl -s ifconfig.co | tr -d '\n')

install() {
	apt update
	apt install jq qrencode
	bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install

	read -d '/n' -r PRIVATE_KEY PUBLIC_KEY < <(xray x25519 | awk '{print $3}')

	echo "$PUBLIC_KEY" >$CONFIG_DIR/pubkey

	TEMP_FILE=$(mktemp)

	curl -s "https://raw.githubusercontent.com/hyperpuncher/xray-wizard/refs/heads/main/config_server_template.json" >"$TEMP_FILE"

	jq --arg privkey "$PRIVATE_KEY" '
		.inbounds[0].streamSettings.realitySettings.privateKey = $privkey
		' "$TEMP_FILE" >$CONFIG

	curl -s "https://raw.githubusercontent.com/hyperpuncher/xray-wizard/refs/heads/main/config_client_template.json" >"$TEMP_FILE"

	jq --arg pubkey "$PUBLIC_KEY" '
		.outbounds[0].streamSettings.realitySettings.publicKey = $pubkey
		' "$TEMP_FILE" >"$CLIENT_CONFIG_TEMPLATE"

}

add() {
	NAME=$1
	UUID=$(xray uuid)
	PUBLIC_KEY=$(cat $CONFIG_DIR/pubkey)
	LINK="vless://$UUID@$IP:443?security=reality&encryption=none&pbk=$PUBLIC_KEY&headerType=none&fp=chrome&type=tcp&flow=xtls-rprx-vision#xray"
	TEMP_FILE=$(mktemp)
	chmod 644 "$TEMP_FILE"

	jq --arg uuid "$UUID" --arg name "$NAME" '
		.inbounds[0].settings.clients += [{
			"id": $uuid, "email": $name, "flow": "xtls-rprx-vision"
		}]' $CONFIG >"$TEMP_FILE"

	mv "$TEMP_FILE" $CONFIG

	jq --arg ip "$IP" --arg uuid "$UUID" --arg pubkey "$PUBLIC_KEY" '
    	.outbounds[0].settings.vnext[0].address = $ip |
		.outbounds[0].settings.vnext[0].users[0].id = $uuid |
    	.outbounds[0].streamSettings.realitySettings.publicKey = $pubkey
		' $CLIENT_CONFIG_TEMPLATE >"$TEMP_FILE"

	mkdir "$CONFIG_DIR/$NAME"
	mv "$TEMP_FILE" "$CONFIG_DIR/$NAME/config.json"

	qrencode -t ANSIUTF8 "$LINK"
	qrencode -o "$CONFIG_DIR/$NAME/qr.png" "$LINK"

	echo "$LINK" | tee "$CONFIG_DIR/$NAME/link"

	systemctl restart xray.service
}

remove() {
	NAME=$1
	TEMP_FILE=$(mktemp)
	chmod 644 "$TEMP_FILE"

	jq --arg name "$NAME" '.inbounds[].settings.clients |= map(select(.email != $name))' $CONFIG >"$TEMP_FILE"

	mv "$TEMP_FILE" $CONFIG

	rm -rf "$CONFIG_DIR/$NAME"

	systemctl restart xray.service
}

list() {
	jq -r '.inbounds[].settings.clients[].email' $CONFIG
}

case $1 in
"-a")
	if [ "$#" -lt 2 ]; then
		echo "Usage: xray-wizard -a <client_name>"
		exit 1
	fi
	add "$2"
	;;
"-r")
	if [ "$#" -lt 2 ]; then
		echo "Usage: xray-wizard -r <client_name>"
		exit 1
	fi
	remove "$2"
	;;
"-l")
	list
	;;
"-i")
	install
	;;
*)
	cat <<EOF
Usage: xray-wizard [options]

Options:
 -a <client_name>  Add new client
 -r <client_name>  Remove client
 -l                List clients
 -i                Setup xray
EOF
	exit 1
	;;
esac
